package com.gjd.UI;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.MenuBar;
import com.vaadin.ui.VerticalLayout;

public class Checkout extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private VerticalLayout Page;
	@AutoGenerated
	private MenuBar Menu;
	@AutoGenerated
	private HorizontalLayout Header;
	@AutoGenerated
	private Label SiteName;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public Checkout() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// Page
		Page = buildPage();
		mainLayout.addComponent(Page, "top:0.0px;left:0.0px;");
		
		return mainLayout;
	}

	@AutoGenerated
	private VerticalLayout buildPage() {
		// common part: create layout
		Page = new VerticalLayout();
		Page.setStyleName("title");
		Page.setImmediate(false);
		Page.setWidth("-1px");
		Page.setHeight("-1px");
		Page.setMargin(false);
		
		// Header
		Header = buildHeader();
		Page.addComponent(Header);
		
		// Menu
		Menu = new MenuBar();
		Menu.setImmediate(false);
		Menu.setWidth("-1px");
		Menu.setHeight("-1px");
		Page.addComponent(Menu);
		
		return Page;
	}

	@AutoGenerated
	private HorizontalLayout buildHeader() {
		// common part: create layout
		Header = new HorizontalLayout();
		Header.setImmediate(false);
		Header.setWidth("-1px");
		Header.setHeight("-1px");
		Header.setMargin(false);
		
		// SiteName
		SiteName = new Label();
		SiteName.setImmediate(false);
		SiteName.setWidth("-1px");
		SiteName.setHeight("-1px");
		SiteName.setValue("Toy Store");
		Header.addComponent(SiteName);
		
		return Header;
	}

}
