package com.gjd.UI.Admin;

import com.vaadin.ui.VerticalLayout;
import java.sql.SQLException;

import com.gjd.model.DatabaseConnection;
import com.vaadin.data.util.sqlcontainer.SQLContainer;
import com.vaadin.data.util.sqlcontainer.query.TableQuery;
import com.vaadin.server.Page;
import com.vaadin.shared.ui.label.ContentMode;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Notification;
import com.vaadin.ui.Table;
import com.vaadin.ui.Table.ColumnGenerator;

public class VendorControl extends VerticalLayout
{

	private static final long serialVersionUID = 3654886303233327083L;
	
	SQLContainer vendorContainer;

	public class RemoveColumnGenerator implements ColumnGenerator
	{

		private static final long serialVersionUID = -1189223015895769902L;

		@Override
		public Object generateCell(Table source, Object itemId, Object columnId)
		{
			final Object item = itemId;
			final Button remove = new Button("X");
			remove.addClickListener(new ClickListener()
			{

				private static final long serialVersionUID = -8605828896793166762L;

				@Override
				public void buttonClick(ClickEvent event)
				{
					try
					{
						vendorContainer.removeItem(item);
						vendorContainer.commit();
						Notification n = new Notification("Success", "Brand removed", Notification.Type.TRAY_NOTIFICATION);
						n.setDelayMsec(500);
						n.show(Page.getCurrent());
					}
					catch (SQLException e)
					{
						Notification n = new Notification("Error", "Error removing brand:" + e.getLocalizedMessage(), Notification.Type.ERROR_MESSAGE);
						n.show(Page.getCurrent());
						e.printStackTrace();
					}
				}
			});
			return remove;
		}
	}

	private Table vendorTable;
	
	public VendorControl()
	{
		setMargin(true);
		setSpacing(true);

		try
		{
			Label header = new Label("<h2>Brands</h2>");
			header.setContentMode(ContentMode.HTML);

			Table brandTable = createVendorTable();
			HorizontalLayout buttons = createButtonLayout();
			
			addComponent(header);
			addComponent(buttons);
			addComponent(brandTable);
		}
		catch (Exception ex)
		{
			ex.printStackTrace(System.err);
		}
	}
	
	
	private Table createVendorTable() throws SQLException
	{
		TableQuery brands = new TableQuery("Vendor", DatabaseConnection.getInstance().getPool());
		vendorContainer = new SQLContainer(brands);
		vendorTable = new Table();
		vendorTable.setContainerDataSource(vendorContainer);

		// Hide the ID column (by default)
		vendorTable.setColumnCollapsingAllowed(true);
		vendorTable.setColumnCollapsed("vendor_id", true);
		vendorTable.setColumnCollapsible("vendor_name", false);

		vendorTable.setWidth("500px");
		// Enable editing (and the associated SQL Magic ;) )
		vendorTable.setEditable(true);

		// Add autogenerated columns
		vendorTable.addGeneratedColumn("remove", new RemoveColumnGenerator());
		vendorTable.addGeneratedColumn("address_id", new AddressPopupColumnGenerator(vendorContainer));

		// Set the headers
		vendorTable.setColumnHeaders("ID", "Vendor Name", "Address", "Remove");
		return vendorTable;
	}

	private HorizontalLayout createButtonLayout()
	{
		HorizontalLayout buttons = new HorizontalLayout();
		buttons.setSpacing(true);
		Button addBrand = new Button("New Vendor");
		addBrand.addClickListener(new ClickListener()
		{

			private static final long serialVersionUID = -3848256903363909965L;

			@SuppressWarnings("unchecked")
			@Override
			public void buttonClick(ClickEvent event)
			{
				Object newVendor = vendorContainer.addItem();
				
				vendorContainer.getItem(newVendor).getItemProperty("vendor_name").setValue("New Vendor");
				try
				{
					//vendorContainer.commit();
					vendorTable.refreshRowCache();
					Notification.show("Success", "Brand created", Notification.Type.HUMANIZED_MESSAGE);
				}
				catch (Exception e)
				{
					Notification.show("Error", "Error creating brand:" + e.getLocalizedMessage(), Notification.Type.ERROR_MESSAGE);
				}
			}
		});

		Button save = new Button("Save");
		save.addClickListener(new ClickListener()
		{

			private static final long serialVersionUID = 4392009671146429000L;

			@Override
			public void buttonClick(ClickEvent event)
			{
				try
				{
					vendorContainer.commit();
					Notification.show("Success", "Vendors saved", Notification.Type.HUMANIZED_MESSAGE);
				}
				catch (SQLException e)
				{
					Notification.show("Error updating vendors: " + e.getLocalizedMessage(), Notification.Type.ERROR_MESSAGE);
				}
			}
		});

		Button reset = new Button("Reset");
		reset.addClickListener(new ClickListener()
		{

			private static final long serialVersionUID = 5741755040045435705L;

			@Override
			public void buttonClick(ClickEvent event)
			{
				try
				{
					vendorContainer.rollback();
					Notification.show("Success", "Vendors reset", Notification.Type.HUMANIZED_MESSAGE);
				}
				catch (SQLException e)
				{
					Notification.show("Error", "Error rolling back transaction:" + e.getLocalizedMessage(), Notification.Type.ERROR_MESSAGE);
				}
			}
		});

		buttons.addComponent(addBrand);
		buttons.addComponent(save);
		buttons.addComponent(reset);

		return buttons;
	}

}